import type { Metadata } from "next";

import "./globals.css";
import AppLayout from "@/layouts/app-layout";

export const metadata: Metadata = {
  title: "Experiment Project",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
